### ISSUE TITLE
Error while running script

### ISSUE THREAD

**Issue by DarthKeizer** [torworld/fastrelay#12]
deb.torproject.org-keyring is already the newest version (2018.08.06).
tor is already the newest version (0.4.1.6-1~d10.buster+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19665  100 19665    0     0   124k      0 --:--:-- --:--:-- --:--:--  125k
gpg: key EE8CBC9E886DDD89: 36 signatures not checked due to missing keys
gpg: key EE8CBC9E886DDD89: "deb.torproject.org archive signing key" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
OK

**Comment by DarthKeizer** [comment]
and then its stuck

**Comment by lunarthegrey** [comment]
@beardlyness, any idea?

**Comment by DarthKeizer** [comment]
Fixed it, dosnt work on the latest version. downgreading OS fixed it. Or manually adjusing to the latest repo should work too
